name: MSBuild

on:
  push:
    branches:
      - master

env:
  SOLUTION_FILE_PATH: BIOS.sln
  BUILD_CONFIGURATION: Release

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Restore NuGet packages
        run: nuget restore ${{ env.SOLUTION_FILE_PATH }}

      - name: Build
        run: msbuild ${{ env.SOLUTION_FILE_PATH }} /m /p:Configuration=${{ env.BUILD_CONFIGURATION }} /p:Platform=x64

      - name: Copy SDL3.dll
        run: copy lib\bins\SDL3.dll x64\Release\

      - name: Create ZIP
        shell: pwsh
        run: |
          Compress-Archive -Path x64\Release\* -DestinationPath BIOS-Build-${{ github.run_number }}.zip

      - name: Create Tag
        shell: pwsh
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag build-${{ github.run_number }}
          git push origin build-${{ github.run_number }}

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: build-${{ github.run_number }}
          name: Build ${{ github.run_number }}
          generate_release_notes: true
          files: BIOS-Build-${{ github.run_number }}.zip
